version: "3.3"
services:
    mysql:
        image: mysql:8.0.18
        ports:
            - "3306:3306"
        volumes:
            - "./mysql/init:/docker-entrypoint-initdb.d"
            - "./mysql/data:/car/lib/mysql"
            - "./mysql/conf.d/my.cnf:/etc/mysql/conf.d/my.cnf"
        environment:
            - MYSQL_ROOT_PASSWORD=root
        command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
        container_name: mysql01
    nginx:
        build: nginx/
        hostname: ng01
        ports:
            - 80:80
        volumes:
            - ./nginx/conf.d:/etc/nginx/conf.d
            - ./nginx/log:/var/log/nginx
        container_name: nginx01
    app:
        build: spring/
        hostname: appserver
        ports:
            - 8080:8080
        volumes:
            
            container_name: spring
        links:
            - mysql
